#+TITLE: NUMSR-PATCHES
#+AUTHOR: Matthew Elwin

* Overview
This package contains scripts and configuration files for unreleased or customized packages used by Northwestern University's MS in Robotics program.
This repository is intended for use with ROS2 Humble on Ubuntu 22.04, and is designed to be an overlay of the standard ROS 2 installation.

** Packages Provided
1. Librealsense2, with Python bindings
2. interbotix ROS packages for using the PincherX 100 Robot arm
3. An updated =ros2 launch= with some not-yet-released bugfixes

** Prerequisites
The following prerequisites can be installed via =apt=, but are likely already installed if you are developing with ROS 2.
1. =python3-vcstool=
2. =python3-colcon-common-extensions=
3. =python3-colcon-mixin=

** Setup
Here are the basic setup instructions.
Essentially this is a ros 2 workspace whose contents are populated with a =.repos= file using =vcs tool=
#+BEGIN_SRC bash
# Make a new ROS2 workspace and enter it
mkdir -p ~/ws/nuws/src
cd ~/ws/nuws

# Clone the repositories
vcs import --recursive --input https://raw.githubusercontent.com/m-elwin/numsr_patches/main/numsr_patches.repos src

# Install dependencies
rosdep install --from-paths src --ignore-src -r -y

# Install non rosdep depencencies
sudo apt install libpoco-dev

# Add the numsr colcon mixin
colcon mixin add numsr_patches file://$(pwd)/src/numsr_patches/index.yaml
colcon mixin update numsr_patches

# Build the workspace
colcon build --mixin numsr

# Install the udev rules
sudo cp src/librealsense/config/99-realsense-libusb.rules /etc/udev/rules.d
sudo cp src/interbotix_ros_core/interbotix_ros_xseries/interbotix_xs_sdk/99-interbotix-udev.rules /etc/udev/rules.d
#+END_SRC

In your =~/.bashrc=, after sourcing =/opt/ros/humble/setup.bash=, source the setup script for the =nuws=
- The line is =source ~/ws/nuws/install/setup.bash=, adjusting the path to =nuws= as appropriate
*** Additional Options
1. If you don't want to add the mixin globally you can invoke it directly with
   =colcon build --mixin-files ./src/numsr_patches/numsr_patches.mixin --mixin numsr=.

** Updating
1. These steps are only needed if you need to update to the latest version.
2. If you just installed this, you are already at the latest version.

Here is how to update the workspace when changes are made to =numsr_patches=. 
#+BEGIN_SRC bash
# Enter the nuws workspace
cd ~/nuws
# update the repositories
vcs import --force --from-url https://raw.githubusercontent.com/m-elwin/numsr_patches/main/numsr_patches.repos src
# update the mixin
colcon mixin update numsr_patches
# Delete the installed files
rm -rf install
# rebuild the workspace
colcon build numsr
#+END_SRC

*** colcon-clean TODO
When [[https://github.com/ruffsl/colcon-clean][colcon-clean]] is officially released it will be worked into the update process.
- Monitor [[https://github.com/colcon/colcon-core/issues/521][Colcon-core Issue #521]] and [[https://github.com/colcon/colcon-core/issues/522][Colcon-core Issue #522]]
